services:
  springboot-app:
    image: jpamapping-image1:tag1 # It is your built application image name:tag
    container_name: jpamappingappcontainer
    ports:
      - "8091:8087"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/JPARelationship?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb
    networks:
      - springjpa-network

  mysqldb:
    image: mysql:8.0 # It is image name:version taken from docker hub
    container_name: jpamappingdbcontainer
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: JPARelationship
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    networks:
      - springjpa-network

networks:
  springjpa-network:
    #driver: bridge